#!/bin/bash
#
# stop-domain
#
# This script is where the action stops happening.  It takes one parameter,
# which is the domain to stop.  If the parameter is omitted, the default
# domain from Consul is used.
#

######################################################################
# SCRIPT CONFIGURATION
######################################################################

# domain to use if hostname parameter is not fully qualified
default_domain=`curl -s 'http://localhost:8500/v1/kv/default-domain?raw'`

######################################################################
# FUNCTIONS
######################################################################

usage(){
    echo
    echo "Usage: $0 <domain>"
    echo
    echo " <domain>: the name of the domain being started"
    echo
    echo " The following structure is expected in Consul:"
    echo
    echo "  /v1/kv/nodes"
    echo "    /<domain>"
    echo "      /<hostname>"
    echo "        /instance-id          unique instance id"
    echo "        /placement            vmhost to on which VM will run"
    echo
    exit 1
}

log(){ echo -e "\e[32m\e[1m--> ${1}...\e[0m"; }
warn(){ echo -e "\e[33m\e[1mWARNING: ${1}\e[0m"; }
error(){ echo -e "\e[31m\e[1mERROR: ${1}\e[0m"; }
fatal(){ echo -e "\e[31m\e[1mFATAL: ${1}\e[0m\n\n  Hint: try '$0 --help'\n"; exit 1; }

consul_param(){ curl -s "http://localhost:8500/v1/kv/nodes/${2}/${1}/${3}?raw"; }

######################################################################
# GATHER DATA
######################################################################

domain=${1:-$default_domain}

# the list of hostnames we're shooting for
declare -a hosts
hosts=( `curl -s "http://localhost:8500/v1/kv/nodes/${domain}/?keys&separator=/" | sed -e 's|nodes/node.qa.consul/||g' -e 's|,| |g' -e 's|[]/"[]||g'` )

######################################################################
# STOP ALL VMs AND BURN THEM WITH FIRE!!!
######################################################################

for host in "${hosts[@]}"; do
    ./remove-vm "${host}.${domain}"
done
