#!/bin/bash
#
# upload-gm
#
# Upload a gold master image to a libvirt volume pool.  There's not much to
# this... it's really just for convenience.
#

######################################################################
# SCRIPT CONFIGURATION
######################################################################

vol=$1
pool=${2:-default}
placement=${3:-localhost}
format=${4:-qcow2}

######################################################################
# FUNCTIONS
######################################################################

usage(){
    echo
    echo "Usage: $0 <gm filename> [<pool>] [<placement>] [<format>]"
    echo
    echo " <gm filename>: the name of the file being uploaded"
    echo " <pool>:        volume pool to upload (default)"
    echo " <placement>:   which host to upload to (localhost)"
    echo " <format>:      format of image (qcow2)"
    echo
    exit 1
}
if [ "$1" = "--help" ]; then usage; fi

log(){ echo -e "\e[32m\e[1m--> ${1}...\e[0m"; }
warn(){ echo -e "\e[33m\e[1mWARNING: ${1}\e[0m"; }
error(){ echo -e "\e[31m\e[1mFATAL: ${1}\e[0m"; }
fatal(){ echo -e "\e[31m\e[1mFATAL: ${1}\e[0m"; exit 1; }

######################################################################
# DO STUFF
######################################################################

vol_exists=$(virsh -c qemu+ssh://${placement}/system vol-list --pool ${pool} | awk 'NR>2 { print $1 }' | grep "^${vol}$" | wc -l)
if [ $vol_exists -eq 0 ]; then
    vol_size=$(stat -Lc%s ${vol})
    log "Creating volume with size '${vol_size}'"
    virsh -c qemu+ssh://${placement}/system vol-create-as ${pool} ${vol} ${vol_size} --format ${format}
fi

log "Uploading image"
virsh -c qemu+ssh://${placement}/system vol-upload --pool ${pool} ${vol} ${vol}
